<?php


namespace Sujit\Messenger;


use Sujit\Messenger\Facades\MessengerFacade;
use Illuminate\Foundation\AliasLoader;
use Illuminate\Support\ServiceProvider;

class MessengerServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        $this->app->bind('messenger', Messenger::class);
        $this->publishes([
            __DIR__ . '/../config/messenger.php' => config_path('messenger.php'),
            __DIR__ . '/../resources/assets/app' => public_path('vendor/messenger'),
        ], 'public');

        $this->mergeConfigFrom(__DIR__ . '/../config/messenger.php', 'messenger');
        $this->loadMigrationsFrom(__DIR__ . '/../database/migrations');

        $this->loadViewsFrom(__DIR__ . '/../resources/views', 'messenger');
        $this->loadRoutesFrom(__DIR__ . '/../routes/web.php');
    }
}
