<?php


namespace Sujit\Messenger\Drivers;


class LongcodeDriver extends Driver
{
    public function send($payload, $token = null)
    {
        return parent::send($payload, $token); // TODO: Change the autogenerated stub
    }
}
